name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint and fix issues
      run: npm run lint -- --fix

    - name: Run unit tests
      run: npm run test:unit

    - name: Start application
      id: start-app
      run: |
        PORT=5173
        while lsof -i :$PORT; do
          PORT=$((PORT + 1))
        done
        echo "PORT=$PORT" >> $GITHUB_ENV
        npm run dev -- --port $PORT &
      env:
        CI: true

    - name: Wait for the app to be available
      run: curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:$PORT

    - name: Run Cypress tests
      uses: cypress-io/github-action@v5
      with:
        start: npm run dev -- --port ${{ env.PORT }}
        wait-on: http://localhost:${{ env.PORT }}
        config-file: cypress.config.js
