name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint and fix issues
      run: npm run lint -- --fix

    - name: Run unit tests
      run: npm run test:unit

    - name: Start application
      id: start-app
      run: |
        npx vite --port 5173 &
        echo $! > .pidfile
        sleep 5  # Wait a few seconds to allow the server to start
        if lsof -i:5173; then
          echo "VITE_PORT=5173" >> $GITHUB_ENV
        else
          echo "VITE_PORT=5174" >> $GITHUB_ENV
        fi

    - name: Run Cypress tests
      run: |
        npx wait-on http://localhost:${{ env.VITE_PORT }}
        npx cypress run --config baseUrl=http://localhost:${{ env.VITE_PORT }}

    - name: Stop application
      if: always()
      run: |
        kill $(cat .pidfile)
        rm .pidfile
